#!/bin/bash

function ACDToolsSyncDeletes {

    # For every file listed by the find command
    for file in ${MATCHED}; do

            if [ "${ACDEXIST}" -eq "0" ]; then
                # File does exist, delete it from Amazon Drive
                ACDToolsLog info "${file#$SEARCHDIR} exists on cloud drive - \
                    deleting"

                DELCMD=$(${RCLONE} delete \
                    ${RCLONEREMOTE}:"${ACDSUBDIR}/${ENCNAME}")
                until ${DELCMD}
                do
                    # Failed delete - sleep and retry
                    ACDToolsLog error "Delete failed, trying again in 30
                        seconds"
                    sleep 30
                done

                ACDToolsLog info "${FILENAME} deleted from cloud drive"

            # Remove the UnionFS hidden object
            rm -rf "${file}"
        else
            ACDToolsLog error "Empty name returned from encfsctl - skipping."
            FAILEDSYNCDELETES=1
        fi

    done

    # Delete the searchdir so that it is not uploaded as an empty directories
    # There's still a chance this can happen with the fix for #27
    if [ -z "${FAILEDSYNCDELETES}" ]; then
        rm -rf "${SEARCHDIR}"
    else
        ACDToolsLog warn "Not clearing .unionfs directory as there were \
            failures."
    fi
}

# Upload local data to Amazon Drive
function ACDToolsUpload {
    # Exit if already being executed
    RUNNINGPID=`cat ${DIR}/upload.pid 2>/dev/null`
    if [ -e /proc/${RUNNINGPID} ] && [ ! -z ${RUNNINGPID} ]; then
        ACDToolsLog error "Upload script already running"
        exit 1
    else
        echo $$ > ${DIR}/upload.pid
    fi

    # Sync Deletes
    ACDToolsSyncDeletes

    # Logic for force syncing on repeated failure
    ULATTEMPTS=0

    # Determine the .unionfs-fuse directory name as to not upload it
    EXCLUDENAME=$(encfsctl encode --extpass="echo ${ENCFSPASS}" \
        ${MOUNTBASE}/acd-encrypted .unionfs-fuse)
    if [ "${#EXCLUDENAME}" -gt "0" ]; then
        ACDToolsLog info "Will not upload ${EXCLUDENAME} directory \
            (.unionfs-fuse)"
        ACDEXCLUDE=" --exclude /${EXCLUDENAME}/* "
        ULCMD=$(${RCLONE} -v copy ${ACDEXCLUDE} \
            ${MOUNTBASE}/local-encrypted/ \
            ${RCLONEREMOTE}:${ACDSUBDIR})
    fi

    # Upload to Cloud Drive
    # Redirect error to `/dev/null` so as not to pollute the output with an
    # `Input/output error`.
    if [ "$(ls -A ${MOUNTBASE}/local-encrypted/* 2> /dev/null)" ] ; then
        until ${ULCMD}
        do
            ULATTEMPTS=$((ULATTEMPTS+1))
            ACDToolsLog error "Some uploads failed - uploading again after a
                sync (attempt ${ULATTEMPTS})"

            if [ "${ULATTEMPTS}" -ge 5 ]; then
                ACDToolsLog error "Upload failed 5 times - giving up"
                exit 1
            fi
            sleep 60
        done
    else
        ACDToolsLog info "${MOUNTBASE}/local-encrypted/* is empty - nothing to 
            upload"
    fi

    ACDToolsLog info "Upload Complete - Syncing changes"

    # Delete local files older than ${LOCALDAYS}
    ACDToolsLocalCleanup

    # Cleanup pidfile
    rm -rf ${DIR}/upload.pid
}
