#!/bin/bash

# Function to mount everything for ACDTools
function ACDToolsMount {
    # Create mountpoint directories
    mkdir -p ${MOUNTBASE}/acd-encrypted/ \
        ${MOUNTBASE}/acd-decrypted/ \
        ${MOUNTBASE}/local-decrypted/ \
        ${MOUNTBASE}/local-encrypted/ \
        ${DATADIR} 2>/dev/null

    MOUNTPREFIX="/${ACDSUBDIR}"

    ACDToolsLog info "Mounting cloud storage Drive"
    screen -dm -S acdtools-mount ${SCRIPTPATH} acdmount

    ACDToolsLog info "Mounting local encrypted filesystem"
    encfs --extpass="echo ${ENCFSPASS}" --reverse \
        ${MOUNTBASE}/local-decrypted/ ${MOUNTBASE}/local-encrypted/

    ACDToolsLog info "Mounting cloud decrypted filesystem"
    encfs --extpass="echo ${ENCFSPASS}" \
        ${MOUNTBASE}/acd-encrypted/${MOUNTPREFIX} ${MOUNTBASE}/acd-decrypted/

    ACDToolsLog info "Mounting UnionFS"
    unionfs-fuse -o cow,allow_other \
        ${MOUNTBASE}/local-decrypted=RW:${MOUNTBASE}/acd-decrypted=RO \
        ${DATADIR}
}

# Reflect unionfs deleted file objects on Amazon Drive
function ACDToolsSyncDeletes {
    ACDMOUNT="${MOUNTBASE}/acd-encrypted/"
    SEARCHDIR="${MOUNTBASE}/local-decrypted/.unionfs-fuse/"

    if [ -d "$SEARCHDIR" ]; then
       MATCHED=$(find ${SEARCHDIR} -type f -name '*_HIDDEN~')
    else
        # There's no need to proceed with this function
        ACDToolsLog info "No .unionfs-fuse/ directory found, nothing to delete"
        return
    fi

    # Set the for delimiter
    IFS=$'\n'

    # For every file listed by the find command
    for file in ${MATCHED}; do

        # Trim off the full path and hidden flag to get the real file path
        FILENAME=$(echo ${file} | grep -oP "^${SEARCHDIR}\K.*")
        FILENAME=${FILENAME%_HIDDEN~}

        ENCNAME=$(encfsctl encode --extpass="echo ${ENCFSPASS}" \
            ${ACDMOUNT} "${FILENAME}")

            if [ "${#ENCNAME}" -gt "0" ]; then
            ACDEXIST=$(${RCLONE} ls --max-depth=1 \
                ${RCLONEREMOTE}:${ACDSUBDIR}/${ENCNAME} > /dev/null 2>&1; \
                echo $?)
            if [ "${ACDEXIST}" -eq "0" ]; then
                # File does exist, delete it from Amazon Drive
                ACDToolsLog info "${file#$SEARCHDIR} exists on cloud drive - \
                    deleting"

                DELCMD=$(${RCLONE} delete \
                    ${RCLONEREMOTE}:"${ACDSUBDIR}/${ENCNAME}")
                until ${DELCMD}
                do
                    # Failed delete - sleep and retry
                    ACDToolsLog error "Delete failed, trying again in 30
                        seconds"
                    sleep 30
                done

                ACDToolsLog info "${FILENAME} deleted from cloud drive"
            else
                ACDToolsLog info "${file#$SEARCHDIR} is not on cloud drive"
            fi

            # Remove the UnionFS hidden object
            rm -rf "${file}"
        else
            ACDToolsLog error "Empty name returned from encfsctl - skipping."
            FAILEDSYNCDELETES=1
        fi

    done

    # Delete the searchdir so that it is not uploaded as an empty directories
    # There's still a chance this can happen with the fix for #27
    if [ -z "${FAILEDSYNCDELETES}" ]; then
        rm -rf "${SEARCHDIR}"
    else
        ACDToolsLog warn "Not clearing .unionfs directory as there were \
            failures."
    fi
}

# Upload local data to Amazon Drive
function ACDToolsUpload {
    # Exit if already being executed
    RUNNINGPID=`cat ${DIR}/upload.pid 2>/dev/null`
    if [ -e /proc/${RUNNINGPID} ] && [ ! -z ${RUNNINGPID} ]; then
        ACDToolsLog error "Upload script already running"
        exit 1
    else
        echo $$ > ${DIR}/upload.pid
    fi

    # Sync Deletes
    ACDToolsSyncDeletes

    # Logic for force syncing on repeated failure
    ULATTEMPTS=0

    # Determine the .unionfs-fuse directory name as to not upload it
    EXCLUDENAME=$(encfsctl encode --extpass="echo ${ENCFSPASS}" \
        ${MOUNTBASE}/acd-encrypted .unionfs-fuse)
    if [ "${#EXCLUDENAME}" -gt "0" ]; then
        ACDToolsLog info "Will not upload ${EXCLUDENAME} directory \
            (.unionfs-fuse)"
        ACDEXCLUDE=" --exclude /${EXCLUDENAME}/* "
        ULCMD=$(${RCLONE} -v copy ${ACDEXCLUDE} \
            ${MOUNTBASE}/local-encrypted/ \
            ${RCLONEREMOTE}:${ACDSUBDIR})
    fi

    # Upload to Cloud Drive
    # Redirect error to `/dev/null` so as not to pollute the output with an
    # `Input/output error`.
    if [ "$(ls -A ${MOUNTBASE}/local-encrypted/* 2> /dev/null)" ] ; then
        until ${ULCMD}
        do
            ULATTEMPTS=$((ULATTEMPTS+1))
            ACDToolsLog error "Some uploads failed - uploading again after a
                sync (attempt ${ULATTEMPTS})"

            if [ "${ULATTEMPTS}" -ge 5 ]; then
                ACDToolsLog error "Upload failed 5 times - giving up"
                exit 1
            fi
            sleep 60
        done
    else
        ACDToolsLog info "${MOUNTBASE}/local-encrypted/* is empty - nothing to 
            upload"
    fi

    ACDToolsLog info "Upload Complete - Syncing changes"

    # Delete local files older than ${LOCALDAYS}
    ACDToolsLocalCleanup

    # Cleanup pidfile
    rm -rf ${DIR}/upload.pid
}

# Delete local data older than ${LOCALDAYS}
function ACDToolsLocalCleanup {
    ACDToolsLog info "Deleting local files older than ${LOCALDAYS} days"

    find ${MOUNTBASE}/local-decrypted/ -type f \
        -ctime +${LOCALDAYS} -exec rm -rf {} \;
}

# Foreground acdcli mount which will keep remounting until unmount file exists
function ACDToolsACDCLIMount {
    while [ ! -f ${DIR}/unmount.acd ]
    do
        ACDToolsLog info "Running cloud storage mount in the foreground"
        ACDToolsUnmount ${MOUNTBASE}/acd-encrypted/

        mkdir -p ${MOUNTBASE}/chunks
        ${PLEXDRIVE} -o allow_other,read_only -v 2 \
            -t ${MOUNTBASE}/chunks \
            --clear-chunk-max-size=32G ${MOUNTBASE}/acd-encrypted/

        ACDToolsLog info "Cloud storage mount exited - checking if to remount in
            a couple of seconds"
        sleep 2
    done

    ACDToolsLog info "The acdcli mount exited cleanly"
    rm -f ${DIR}/unmount.acd
}
