#!/bin/bash

# Upload local data to Amazon Drive
function ACDToolsUpload {
    # Exit if already being executed
    RUNNINGPID=`cat ${DIR}/upload.pid 2>/dev/null`
    if [ -e /proc/${RUNNINGPID} ] && [ ! -z ${RUNNINGPID} ]; then
        ACDToolsLog error "Upload script already running"
        exit 1
    else
        echo $$ > ${DIR}/upload.pid
    fi

    # Sync Deletes
    ACDToolsSyncDeletes

    # Logic for force syncing on repeated failure
    ULATTEMPTS=0

    # Determine the .unionfs-fuse directory name as to not upload it
    EXCLUDENAME=$(encfsctl encode --extpass="echo ${ENCFSPASS}" \
        ${MOUNTBASE}/acd-encrypted .unionfs-fuse)
    if [ "${#EXCLUDENAME}" -gt "0" ]; then
        ACDToolsLog info "Will not upload ${EXCLUDENAME} directory \
            (.unionfs-fuse)"
        ACDEXCLUDE=" --exclude /${EXCLUDENAME}/* "
        ULCMD=$(${RCLONE} -v copy ${ACDEXCLUDE} \
            ${MOUNTBASE}/local-encrypted/ \
            ${RCLONEREMOTE}:${ACDSUBDIR})
    fi

    # Upload to Cloud Drive
    # Redirect error to `/dev/null` so as not to pollute the output with an
    # `Input/output error`.
    if [ "$(ls -A ${MOUNTBASE}/local-encrypted/* 2> /dev/null)" ] ; then
        until ${ULCMD}
        do
            ULATTEMPTS=$((ULATTEMPTS+1))
            ACDToolsLog error "Some uploads failed - uploading again after a
                sync (attempt ${ULATTEMPTS})"

            if [ "${ULATTEMPTS}" -ge 5 ]; then
                ACDToolsLog error "Upload failed 5 times - giving up"
                exit 1
            fi
            sleep 60
        done
    else
        ACDToolsLog info "${MOUNTBASE}/local-encrypted/* is empty - nothing to 
            upload"
    fi

    ACDToolsLog info "Upload Complete - Syncing changes"

    # Delete local files older than ${LOCALDAYS}
    ACDToolsLocalCleanup

    # Cleanup pidfile
    rm -rf ${DIR}/upload.pid
}
